---
- name: Install required dependencies
  apt:
    name:
      - wget
      - gnupg
      - fontconfig
    state: present
    update_cache: yes
  become: yes

- name: Download Jenkins repository key to temporary location
  ansible.builtin.get_url:
    url: 'https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key'
    dest: '/tmp/jenkins-keyring.asc'
    mode: '0644'

- name: Move Jenkins key to keyrings directory
  ansible.builtin.copy:
    src: '/tmp/jenkins-keyring.asc'
    dest: '/usr/share/keyrings/jenkins-keyring.asc'
    mode: '0644'
    remote_src: yes  
  become: yes

- name: Remove temporary Jenkins key file
  ansible.builtin.file:
    path: '/tmp/jenkins-keyring.asc'
    state: absent
  become: yes

- name: Add Jenkins repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]
      https://pkg.jenkins.io/debian-stable binary/
    state: present
    filename: jenkins
  become: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present
  become: yes

- name: Ensure Jenkins service is enabled and started
  ansible.builtin.systemd:
    name: jenkins
    enabled: yes
    state: started
  become: yes

- name: Set Jenkins environment variable
  lineinfile:
    path: /etc/environment
    line: "JENKINS_PORT={{ jenkins_port }}"
    state: present
  become: yes
