sonarqube_version: "latest"
postgres_version: "15"
sonarqube_db_name: "sonarqube"
sonarqube_db_user: "sonar"
sonarqube_db_password: "sonar_password"  # Secure this in production
sonarqube_port: "9000"
docker_network: "sonarqube_network"