apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivolve-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HadeerAlaa542/CloudDevOpsProject.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
