---
- name: Pull SonarQube Docker image
  docker_image:
    name: sonarqube:latest
    source: pull
  become: yes

- name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    state: started
    restart_policy: always
    ports:
      - "{{ sonarqube_port }}:9000"
    env:
      SONAR_JDBC_URL: "jdbc:postgresql://localhost:5432/sonar"  # Requires a DB (simplified here)
      SONAR_JDBC_USERNAME: "sonar"
      SONAR_JDBC_PASSWORD: "sonar"
  become: yes

- name: Set SonarQube environment variable
  lineinfile:
    path: /etc/environment
    line: "SONARQUBE_PORT={{ sonarqube_port }}"
    state: present
  become: yes
