plugin: aws_ec2
regions:
  - us-east-1  
filters:
  instance-state-name: running
  tag:Name: [master, slave] 
keyed_groups:
  - key: tags.Name
    separator: ""
    prefix: "tag_Name"
hostnames:
  - public-ip-address
compose:
  ansible_host: public_ip_address
