---
- name: Configure all instances with common packages
  hosts: all
  roles:
    - common

- name: Configure master with Jenkins
  hosts: tag_Namemaster
  roles:
    - jenkins
    
- name: Configure slave with SonarQube
  hosts: tag_Nameslave
  become: yes
  roles:
    - SonarQube
